---
title: "Gerrymandering Progress Report"
author: "Peter Gao, Casper Neo, Nishesh Sharma"
date: "February 27, 2017"
output: pdf_document
---

## Introduction

Gerrymandering refers to the practice of redrawing the boundaries of an electoral constituency to favor a chosen group, typically a racial group or political party. In the United States, most states require electoral districts to be redrawn every ten years, coinciding with the decennial U.S. census. Ostensibly, this process is meant to update districts according to demographic change, but in many states the redistricting process is controlled by the political party in power. As such, political parties looking to consolidate their power may use the redistricting process to draw districts that put their representatives in favorable elections. 

In recent years, growth in computing power and openly accessible data has contributed to an increased interest in quantifying gerrymandering. The issue of gerrymandering is especially vital today, as the Supreme Court is due to decide on multiple gerrymandering cases in 2017. However, the government still has yet to settle the question of how precisely to measure and define gerrymandering. What does gerrymandering look like in a heavily Republican state? Or a perennially contested swing state? Many political scientists and statisticians have proposed tests and metrics for identifying and defining gerrymandering; for our project, we have replicated some of these measures of gerrymandering and hope to compare and contrast them.

## Guiding Example

Following the 2010 U.S. Census, the North Carolina state legislature (controlled by Republicans at the time) approved a new redistricting plan. Democrats and some critics complained that Republicans had worked to pack, or concentrate, Democratic voters in a few, heavily Democratic districts, while distributing Republican votes in such a way to give Republicans a narrow but stable lead in the remaining districts (a practice commonly referred to as cracking and packing). These critics would go on to point to the Democrats' poor showing in the 2012 Congressional elections as a reflection of the unfair redistricting process. [^1]

[^1]: Ballotpedia.

To (naively) evaluate this claim, we used the efficiency gap measure proposed by Nicholas Stephanopoulos and Eric McGhee (2015). Simply put, the efficiency gap measures the difference between the number of votes wasted by Democrats and the number of votes wasted by Republicans. Wasted votes are those cast for losing candidates added to those cast for winning candidates above the number needed to win an election, i.e. the superfluous votes. The absolute difference in wasted votes between the two parties is divided by the total votes cast in the election in the state in order to enable comparison. We calculated the efficiency gap for elections from 2006-2016 (note that we calculated our efficiency gap by subtracting Republican wasted votes from Democratic wasted votes, so a positive efficiency gap reflects unfavorable conditions for Democrats)

```{r, echo = F, cache = T, fig.height = 3.5}
hr2016 <- read.csv("C:/Users/pgao/Dropbox/Winter 2017/Multiple Testing/2016_NC_USHR_summary.csv")
hr2014 <- read.csv("C:/Users/pgao/Dropbox/Winter 2017/Multiple Testing/2014_NC_USHR_summary.csv")
hr2012 <- read.csv("C:/Users/pgao/Dropbox/Winter 2017/Multiple Testing/2012_NC_USHR_summary.csv")
hr2010 <- read.csv("C:/Users/pgao/Dropbox/Winter 2017/Multiple Testing/2010_NC_USHR_summary.csv")
hr2008 <- read.csv("C:/Users/pgao/Dropbox/Winter 2017/Multiple Testing/2008_NC_USHR_summary.csv")
hr2006 <- read.csv("C:/Users/pgao/Dropbox/Winter 2017/Multiple Testing/2006_NC_USHR_summary.csv")


efficiency.gap.nc <- function (data) {
  rep.wasted <- 0
  dem.wasted <- 0
  for (race in levels(data$contest.name)){
    needed <- .5*sum(subset(data, (contest.name == race) & (party.name == 'DEM' | party.name == 'REP'))$total.votes)
    dem.votes <- subset(data, (contest.name == race) & (party.name == 'DEM'))$total.votes
    rep.votes <- subset(data, (contest.name == race) & (party.name == 'REP'))$total.votes
    if (dem.votes > rep.votes){
      rep.wasted <- rep.wasted + rep.votes
      dem.wasted <- dem.wasted + (dem.votes - needed)
    } else {
      rep.wasted <- rep.wasted + (rep.votes - needed)
      dem.wasted <- dem.wasted + dem.votes
    }
  }
  gap <- (dem.wasted - rep.wasted)/(dem.wasted + rep.wasted)
  return (gap)
}
pre <- c(efficiency.gap.nc(hr2006),efficiency.gap.nc(hr2008), efficiency.gap.nc(hr2010))
post <- c(efficiency.gap.nc(hr2012), efficiency.gap.nc(hr2014), efficiency.gap.nc(hr2016))

plot(seq(2006, 2016, 2), c(efficiency.gap.nc(hr2006),efficiency.gap.nc(hr2008), efficiency.gap.nc(hr2010),
                           efficiency.gap.nc(hr2012), efficiency.gap.nc(hr2014), efficiency.gap.nc(hr2016)),
     ylab = 'efficiency gap', xlab = 'year', main = "Figure 1. Efficiency Gap (D - R) in NC Congressional Race")
```

We could also try to perform a two-sample $t$ test, but we note that elections are not independent of each other, making such a test unusable. As such, this example illustrates a fundamental problem in thinking about gerrymandering: even when a trend appears to reflect gerrymandering, the complexity of politics, geography, and demography make it difficult to set a universal fair standard against which we could compare potentially gerrymandered districts. Even if we could establish that the efficiency gap was significantly different post-2010, we would still need to come to the consensus that efficiency gap is an effective way to measure gerrymandering.

## Methods Implemented

### Efficiency Gap (Stephanopoulos and McGhee 2015)

As outlined above, the efficiency gap measures the difference in wasted votes.

### Lopsided Victories (Wang 2016)